CREATE TABLE baili_member
(
    uid BIGINT(20) unsigned NOT NULL,
    employee_id CHAR(20),
    gender TINYINT(1) unsigned,
    nickname VARCHAR(40) DEFAULT '' NOT NULL,
    uname VARCHAR(40) DEFAULT '' NOT NULL,
    passwd VARCHAR(40),
    email VARCHAR(40) DEFAULT '',
    portrait VARCHAR(160) DEFAULT '',
    big_portrait VARCHAR(160) DEFAULT '',
    phone CHAR(11),
    reg_time INT(10) unsigned NOT NULL,
    login_num INT(10) unsigned DEFAULT '0' NOT NULL,
    last_login INT(10) unsigned NOT NULL,
    last_ip VARCHAR(50) NOT NULL,
    is_supper TINYINT(3) DEFAULT '0',
    timeline TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    union_id VARCHAR(32)
);
CREATE INDEX `index` ON baili_member (uname, passwd);
CREATE UNIQUE INDEX uid ON baili_member (uid);
CREATE TABLE baili_quartz_job
(
    id BIGINT(20) unsigned PRIMARY KEY NOT NULL AUTO_INCREMENT,
    job_key VARCHAR(64) NOT NULL COMMENT '任务名称',
    job_group VARCHAR(64) NOT NULL COMMENT '任务组',
    job_status INT(4) DEFAULT '0' NOT NULL COMMENT '任务状态(0:正常，99:禁用)',
    job_cron_express VARCHAR(64) NOT NULL COMMENT '任务时间表达式，提醒时间',
    remarks VARCHAR(500) COMMENT '备注信息拓展字段',
    job_desc VARCHAR(64) COMMENT '任务描述',
    job_params VARCHAR(128) COMMENT '扩展字段，存储相关信息',
    gmt_create DATETIME,
    gmt_modified DATETIME,
    is_deleted INT(4) DEFAULT '0' NOT NULL COMMENT '是否已删除：0 未删除，1 已删除'
);
CREATE UNIQUE INDEX trumpchi_qrtz_job_job_key_job_group_unique ON baili_quartz_job (job_key, job_group);
CREATE TABLE baili_student
(
    id BIGINT(20) PRIMARY KEY NOT NULL COMMENT '主键' AUTO_INCREMENT,
    number BIGINT(20),
    name VARCHAR(255),
    gmt_create DATETIME COMMENT '记录创建时间',
    gmt_modified DATETIME COMMENT '记录修改时间'
);
CREATE TABLE qrtz_blob_triggers
(
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    BLOB_DATA BLOB,
    CONSTRAINT `PRIMARY` PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    CONSTRAINT qrtz_blob_triggers_ibfk_1 FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES qrtz_triggers (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);
CREATE TABLE qrtz_calendars
(
    SCHED_NAME VARCHAR(120) NOT NULL,
    CALENDAR_NAME VARCHAR(200) NOT NULL,
    CALENDAR BLOB NOT NULL,
    CONSTRAINT `PRIMARY` PRIMARY KEY (SCHED_NAME, CALENDAR_NAME)
);
CREATE TABLE qrtz_cron_triggers
(
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    CRON_EXPRESSION VARCHAR(200) NOT NULL,
    TIME_ZONE_ID VARCHAR(80),
    CONSTRAINT `PRIMARY` PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    CONSTRAINT qrtz_cron_triggers_ibfk_1 FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES qrtz_triggers (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);
CREATE TABLE qrtz_fired_triggers
(
    SCHED_NAME VARCHAR(120) NOT NULL,
    ENTRY_ID VARCHAR(95) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    INSTANCE_NAME VARCHAR(200) NOT NULL,
    FIRED_TIME BIGINT(13) NOT NULL,
    SCHED_TIME BIGINT(13) NOT NULL,
    PRIORITY INT(11) NOT NULL,
    STATE VARCHAR(16) NOT NULL,
    JOB_NAME VARCHAR(200),
    JOB_GROUP VARCHAR(200),
    IS_NONCONCURRENT VARCHAR(1),
    REQUESTS_RECOVERY VARCHAR(1),
    CONSTRAINT `PRIMARY` PRIMARY KEY (SCHED_NAME, ENTRY_ID)
);
CREATE TABLE qrtz_job_details
(
    SCHED_NAME VARCHAR(120) NOT NULL,
    JOB_NAME VARCHAR(200) NOT NULL,
    JOB_GROUP VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(250),
    JOB_CLASS_NAME VARCHAR(250) NOT NULL,
    IS_DURABLE VARCHAR(1) NOT NULL,
    IS_NONCONCURRENT VARCHAR(1) NOT NULL,
    IS_UPDATE_DATA VARCHAR(1) NOT NULL,
    REQUESTS_RECOVERY VARCHAR(1) NOT NULL,
    JOB_DATA BLOB,
    CONSTRAINT `PRIMARY` PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
);
CREATE TABLE qrtz_locks
(
    SCHED_NAME VARCHAR(120) NOT NULL,
    LOCK_NAME VARCHAR(40) NOT NULL,
    CONSTRAINT `PRIMARY` PRIMARY KEY (SCHED_NAME, LOCK_NAME)
);
CREATE TABLE qrtz_paused_trigger_grps
(
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    CONSTRAINT `PRIMARY` PRIMARY KEY (SCHED_NAME, TRIGGER_GROUP)
);
CREATE TABLE qrtz_scheduler_state
(
    SCHED_NAME VARCHAR(120) NOT NULL,
    INSTANCE_NAME VARCHAR(200) NOT NULL,
    LAST_CHECKIN_TIME BIGINT(13) NOT NULL,
    CHECKIN_INTERVAL BIGINT(13) NOT NULL,
    CONSTRAINT `PRIMARY` PRIMARY KEY (SCHED_NAME, INSTANCE_NAME)
);
CREATE TABLE qrtz_simple_triggers
(
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    REPEAT_COUNT BIGINT(7) NOT NULL,
    REPEAT_INTERVAL BIGINT(12) NOT NULL,
    TIMES_TRIGGERED BIGINT(10) NOT NULL,
    CONSTRAINT `PRIMARY` PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    CONSTRAINT qrtz_simple_triggers_ibfk_1 FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES qrtz_triggers (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);
CREATE TABLE qrtz_simprop_triggers
(
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    STR_PROP_1 VARCHAR(512),
    STR_PROP_2 VARCHAR(512),
    STR_PROP_3 VARCHAR(512),
    INT_PROP_1 INT(11),
    INT_PROP_2 INT(11),
    LONG_PROP_1 BIGINT(20),
    LONG_PROP_2 BIGINT(20),
    DEC_PROP_1 DECIMAL(13,4),
    DEC_PROP_2 DECIMAL(13,4),
    BOOL_PROP_1 VARCHAR(1),
    BOOL_PROP_2 VARCHAR(1),
    CONSTRAINT `PRIMARY` PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    CONSTRAINT qrtz_simprop_triggers_ibfk_1 FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES qrtz_triggers (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);
CREATE TABLE qrtz_triggers
(
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    JOB_NAME VARCHAR(200) NOT NULL,
    JOB_GROUP VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(250),
    NEXT_FIRE_TIME BIGINT(13),
    PREV_FIRE_TIME BIGINT(13),
    PRIORITY INT(11),
    TRIGGER_STATE VARCHAR(16) NOT NULL,
    TRIGGER_TYPE VARCHAR(8) NOT NULL,
    START_TIME BIGINT(13) NOT NULL,
    END_TIME BIGINT(13),
    CALENDAR_NAME VARCHAR(200),
    MISFIRE_INSTR SMALLINT(2),
    JOB_DATA BLOB,
    CONSTRAINT `PRIMARY` PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    CONSTRAINT qrtz_triggers_ibfk_1 FOREIGN KEY (SCHED_NAME, JOB_NAME, JOB_GROUP) REFERENCES qrtz_job_details (SCHED_NAME, JOB_NAME, JOB_GROUP)
);
CREATE INDEX SCHED_NAME ON qrtz_triggers (SCHED_NAME, JOB_NAME, JOB_GROUP);